version: '3.8'
services:
    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        environment:
            - PGADMIN_DEFAULT_EMAIL=lucastashan@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=12345
        ports:
            - "89:80"
        networks:
            - postgres-network
    postgres:
        image: postgres:10
        container_name: postgres10_container
        environment:
            - POSTGRES_USER=trust
            - POSTGRES_PASSWORD=a12345678
        ports:
            - "5432:5432"
        networks:
            - postgres-network
networks:
    postgres-network:
        driver: bridge